/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2210020169_uji;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pkg2210020169_uji.dbCRUD;
/**
 *
 * @author ASUS
 */
public class karyawanFrame extends javax.swing.JFrame {
    private String url ="jdbc:mysql://localhost:3306/2210020169_periklanan";
    private String user ="root";
    private String pass ="";
    
    private Connection KoneksiDatabase;
    private mainFrame mainFrame;
    /**
     * Creates new form karyawanFrame
     */
    public karyawanFrame(mainFrame mainFrame) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.mainFrame = mainFrame;
        
        try {
            Driver driverku = new com.mysql.jdbc.Driver();
            DriverManager.registerDriver(driverku);
            KoneksiDatabase = DriverManager.getConnection(url, user, pass);
            System.err.println("Frame Berhasil dikoneksikan ke database");
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtNotelp = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPosisi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtIK = new javax.swing.JTextField();
        txtNK = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Alamat");

        jLabel2.setText("Nama Karyawan");

        jLabel4.setText("No Telepon");

        jButton4.setText("Simpan Statment DBCRUD");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT/UPDATE");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        jLabel7.setText("Posisi");

        txtPosisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPosisiActionPerformed(evt);
            }
        });

        jButton1.setText("Simpan Prepared Statement Manual");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Karyawan");

        jButton2.setText("Simpan Prepareed Dari dbCRUD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIKActionPerformed(evt);
            }
        });

        jButton3.setText("Simpan Statement Manual");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtIK, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(232, 232, 232)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNK, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(307, 307, 307)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton2))))
                .addGap(49, 49, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, txtAlamat, txtPosisi});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNotelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEdit, btnHapus});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String id_karyawan = txtIK.getText();
            String nama_karyawan = txtNK.getText();
            String alamat = txtAlamat.getText();
            String no_telp = txtNotelp.getText();
            String posisi = txtPosisi.getText();

            new dbCRUD().SimpanKARYAWANStatement(id_karyawan,nama_karyawan,alamat,no_telp,posisi);
        } catch(Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainFrame.setVisible(true); // Tampilkan kembali mainFrame
        this.dispose(); // Tutup karyawanFrame
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            // Ambil ID karyawan dari field teks
            String id_karyawan = txtIK.getText();

            // Pastikan ID karyawan tidak kosong
            if (id_karyawan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Karyawan tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Query untuk menghapus data karyawan berdasarkan ID
            String sqlHapus = "DELETE FROM karyawan WHERE id_karyawan = ?";
            PreparedStatement perintahHapus = KoneksiDatabase.prepareStatement(sqlHapus);
            perintahHapus.setString(1, id_karyawan);

            int affectedRows = perintahHapus.executeUpdate(); // Eksekusi query

            // Cek apakah ada baris yang terpengaruh
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ID KARYAWAN tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Tutup PreparedStatement
            perintahHapus.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat menghapus data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {
            // Ambil ID karyawan dari field teks
            String id_karyawan = txtIK.getText();

            // Pastikan ID karyawan tidak kosong
            if (id_karyawan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID KARYAWAN tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ambil data baru dari field teks
            String nama_karyawan = txtNK.getText();
            String alamat = txtAlamat.getText();
            String no_telp = txtNotelp.getText();
            String posisi = txtPosisi.getText();

            // Query untuk mengupdate data karyawan berdasarkan ID
            String sqlUpdate = "UPDATE karyawan SET nama_karyawan = ?, alamat = ?, no_telp = ?, posisi = ? WHERE id_karyawan = ?";
            PreparedStatement perintahUpdate = KoneksiDatabase.prepareStatement(sqlUpdate);
            perintahUpdate.setString(1, nama_karyawan);
            perintahUpdate.setString(2, alamat);
            perintahUpdate.setString(3, no_telp);
            perintahUpdate.setString(4, posisi);
            perintahUpdate.setString(5, id_karyawan);

            int affectedRows = perintahUpdate.executeUpdate(); // Eksekusi query

            // Cek apakah ada baris yang terpengaruh
            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate!", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "ID Karyawan tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Tutup PreparedStatement
            perintahUpdate.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat mengupdate data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtPosisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPosisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPosisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String SimpanData = "INSERT INTO karyawan (id_karyawan, nama_karyawan, alamat, no_telp, posisi) VALUES (?, ?, ?, ?, ?)";
            Statement cekPrimaryKey = KoneksiDatabase.createStatement();
            ResultSet hasilcekPrimary = cekPrimaryKey.executeQuery("SELECT*FROM karyawan WHERE id_karyawan='"+txtIK.getText()+"'");

            if (hasilcekPrimary.next()){
                JOptionPane.showMessageDialog(null,"Kode Primary Key sudah Terdaftar");
                hasilcekPrimary.close();
                cekPrimaryKey.close();
            } else {
                PreparedStatement perintahSimpan = KoneksiDatabase.prepareStatement(SimpanData);
                perintahSimpan.setString(1,txtIK.getText());
                perintahSimpan.setString(2,txtNK.getText());
                perintahSimpan.setString(3,txtAlamat.getText());
                perintahSimpan.setString(4,txtNotelp.getText());
                perintahSimpan.setString(5,txtPosisi.getText());
                perintahSimpan.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

                perintahSimpan.close();
                hasilcekPrimary.close();
                cekPrimaryKey.close();
            }
        } catch (Exception e) {
            System.err.println(e.toString());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new dbCRUD().SimpanKARYAWANPreparedstmt(txtIK.getText(), txtNK.getText(), txtAlamat.getText(), txtNotelp.getText(), txtPosisi.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIKActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String id_karyawan = txtIK.getText();
            String nama_karyawan = txtNK.getText();
            String alamat = txtAlamat.getText();
            String no_telp = txtNotelp.getText();
            String posisi = txtPosisi.getText();
            String SQL = "INSERT INTO karyawan (id_karyawan, nama_karyawan, alamat, no_telp, posisi) VALUE('"+ id_karyawan + "','" + nama_karyawan + "','" + alamat + "','" + no_telp + "','" + posisi + "')";

            Statement perintah = KoneksiDatabase.createStatement();
            ResultSet hasil = perintah.executeQuery("SELECT*FROM karyawan WHERE id_karyawan ='"+id_karyawan+"'");

            if (hasil.next()){
                JOptionPane.showMessageDialog(null,"ID KARYAWAN sudah terdaftar");
                hasil.close();
                perintah.close();
            } else {
                perintah.executeUpdate(SQL);
                perintah.close();
                hasil.close();
                JOptionPane.showMessageDialog(null,"Data Berhasil disimpan");
            }
        } catch(Exception e){

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karyawanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karyawanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karyawanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karyawanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Buat dan tampilkan mainFrame */
        mainFrame mainFrameInstance = new mainFrame(); // Buat instance mainFrame
        mainFrameInstance.setVisible(true); // Tampilkan mainFrame

        /* Buat dan tampilkan karyawanFrame */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new karyawanFrame(mainFrameInstance).setVisible(true); // Pass mainFrame instance ke karyawanFrame
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtIK;
    private javax.swing.JTextField txtNK;
    private javax.swing.JTextField txtNotelp;
    private javax.swing.JTextField txtPosisi;
    // End of variables declaration//GEN-END:variables
}
